# Generated by Django 3.2.4 on 2021-06-26 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gcode',
            fields=[
                ('ma', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mota', models.TextField()),
                ('markupdinhmuc', models.FloatField()),
            ],
            options={
                'db_table': 'gcodedb_gcode',
            },
        ),
        migrations.CreateModel(
            name='GDV',
            fields=[
                ('gdvcode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lydoout',
            fields=[
                ('lydooutcode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lydowin',
            fields=[
                ('lydowincode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('suppliercode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
                ('duyetpomax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquirycode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('datesubmitbid', models.DateField()),
                ('clientcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Inquiry', to='gcodedb.client')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contractnoclient', models.CharField(max_length=50)),
                ('datesign', models.DateField()),
                ('dealine1', models.DateField()),
                ('dealine2', models.DateField()),
                ('sellcost', models.FloatField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=5)),
                ('datedeliverylatest', models.DateField()),
                ('clientcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Contract', to='gcodedb.client')),
            ],
        ),
        migrations.CreateModel(
            name='G1code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kymahieuinq', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('bộ', 'bộ'), ('gói', 'gói'), ('thùng', 'thùng'), ('m', 'm'), ('l', 'l'), ('g', 'g'), ('kg', 'kg'), ('pcs', 'pcs')], default='pcs', max_length=20)),
                ('qtyinq', models.FloatField()),
                ('nsxinq', models.CharField(max_length=10)),
                ('sttitb', models.IntegerField()),
                ('groupitb', models.CharField(max_length=5)),
                ('sales', models.CharField(choices=[('TuanLQ', 'TuanLQ'), ('TuanNT', 'TuanNT'), ('TramNB', 'TramNB'), ('ThuyLH', 'ThuyLH'), ('HungTC', 'HungTC'), ('HungND', 'HungND')], default='TuanLQ', max_length=10)),
                ('dongiamuainq', models.FloatField()),
                ('thanhtienmuainq', models.FloatField()),
                ('dongiachaoinq', models.FloatField()),
                ('thanhtienchaoinq', models.FloatField()),
                ('markupinq', models.FloatField()),
                ('resultinq', models.CharField(choices=[('Win', 'Win'), ('Out', 'Out')], default='Win', max_length=10)),
                ('ngaywin', models.DateField(null=True)),
                ('ngayout', models.DateField(null=True)),
                ('ghichu', models.TextField(null=True)),
                ('dateupdate', models.DateField(auto_now_add=True)),
                ('gcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Gcode', to='gcodedb.gcode')),
                ('gdvinq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gcodedb.gdv')),
                ('inquirycode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Inquiry', to='gcodedb.inquiry')),
                ('lydooutcode', models.ManyToManyField(related_name='lydoout', to='gcodedb.lydoout')),
                ('lydowincode', models.ManyToManyField(related_name='lydowin', to='gcodedb.lydowin')),
                ('suppliercode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Supplier', to='gcodedb.supplier')),
            ],
            options={
                'unique_together': {('gcode', 'inquirycode')},
            },
        ),
    ]
