# Generated by Django 3.2.4 on 2021-07-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientcode', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'gcodedb_client',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractcode', models.CharField(max_length=50)),
                ('contractnoclient', models.CharField(max_length=50)),
                ('datesign', models.DateField()),
                ('dealine1', models.DateField()),
                ('dealine2', models.DateField()),
                ('sellcost', models.FloatField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], default='Open', max_length=5)),
                ('datedeliverylatest', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Contractclient', to='gcodedb.client')),
            ],
        ),
        migrations.CreateModel(
            name='Danhgiacode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danhgiacode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='G1code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g1code', models.CharField(max_length=40)),
                ('kymahieuinq', models.CharField(max_length=100)),
                ('unitinq', models.CharField(choices=[('bộ', 'bộ'), ('gói', 'gói'), ('thùng', 'thùng'), ('m', 'm'), ('l', 'l'), ('g', 'g'), ('kg', 'kg'), ('pcs', 'pcs')], default='pcs', max_length=20)),
                ('qtyinq', models.FloatField()),
                ('xuatxuinq', models.CharField(max_length=100)),
                ('nsxinq', models.CharField(max_length=50)),
                ('sttitb', models.IntegerField()),
                ('groupitb', models.CharField(max_length=5)),
                ('sales', models.CharField(choices=[('TuanLQ', 'TuanLQ'), ('TuanNT', 'TuanNT'), ('TramNB', 'TramNB'), ('ThuyLH', 'ThuyLH'), ('HungTC', 'HungTC'), ('HungND', 'HungND')], default='TuanLQ', max_length=10)),
                ('dongiamuainq', models.FloatField()),
                ('dongiachaoinq', models.FloatField()),
                ('markupinq', models.FloatField()),
                ('resultinq', models.CharField(blank=True, choices=[('Win', 'Win'), ('Out', 'Out')], default='Win', max_length=10, null=True)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('dateupdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='G2code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g2code', models.CharField(max_length=40)),
                ('dongiachaohdb', models.FloatField(null=True)),
                ('pono', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('dateupdate', models.DateField()),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_g2codecontract', to='gcodedb.contract')),
                ('g1code', models.OneToOneField(limit_choices_to={'resultinq': 'Win'}, on_delete=django.db.models.deletion.PROTECT, related_name='fk_g2codeg1code', to='gcodedb.g1code')),
            ],
        ),
        migrations.CreateModel(
            name='Gcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(max_length=20)),
                ('mota', models.TextField()),
                ('markupdinhmuc', models.FloatField()),
                ('ngaywin', models.DateField(blank=True, null=True)),
                ('ngayout', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gcodedb_gcode',
            },
        ),
        migrations.CreateModel(
            name='GDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdvcode', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lydoout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lydooutcode', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lydowin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lydowincode', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliercode', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=200)),
                ('duyetpomax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tienve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtytienve', models.FloatField(null=True)),
                ('dongiatienve', models.FloatField(null=True)),
                ('g2code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fk_tienveg2code', to='gcodedb.g2code')),
            ],
        ),
        migrations.CreateModel(
            name='POdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motapo', models.TextField(null=True)),
                ('kymahieupo', models.CharField(max_length=100, null=True)),
                ('unitpo', models.CharField(choices=[('bộ', 'bộ'), ('gói', 'gói'), ('thùng', 'thùng'), ('m', 'm'), ('l', 'l'), ('g', 'g'), ('kg', 'kg'), ('pcs', 'pcs')], default='pcs', max_length=20, null=True)),
                ('qtypo', models.FloatField()),
                ('xuatxupo', models.CharField(max_length=100, null=True)),
                ('nsxpo', models.CharField(max_length=50, null=True)),
                ('dongiamuapo', models.FloatField(null=True)),
                ('ghichu', models.TextField(null=True)),
                ('dateupdate', models.DateField()),
                ('g2code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fk_pog2code', to='gcodedb.g2code')),
                ('gdvpo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pogdv', to='gcodedb.gdv')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_g2codesupplier', to='gcodedb.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Phat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtyphat', models.FloatField(null=True)),
                ('tongphat', models.FloatField(null=True)),
                ('lydophat', models.TextField(null=True)),
                ('dateupdate', models.DateField()),
                ('g2code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fk_phatg2code', to='gcodedb.g2code')),
                ('gdvphat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_phatgdv', to='gcodedb.gdv')),
            ],
        ),
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtykho', models.FloatField(null=True)),
                ('dongiafreight', models.FloatField(null=True)),
                ('ngaynhapkho', models.DateField(null=True)),
                ('dateupdate', models.DateField()),
                ('g2code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fk_khog2code', to='gcodedb.g2code')),
                ('gdvkho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_khogdv', to='gcodedb.gdv')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquirycode', models.CharField(max_length=50)),
                ('datesubmitbid', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Inquiryclient', to='gcodedb.client')),
            ],
            options={
                'db_table': 'gcodedb_inquiry',
            },
        ),
        migrations.CreateModel(
            name='Giaohang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtygiaohang', models.FloatField(null=True)),
                ('ngaygiaohang', models.DateField(null=True)),
                ('dateupdate', models.DateField()),
                ('g2code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fk_giaohangg2code', to='gcodedb.g2code')),
                ('gdvgiaohang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_giaohanggdv', to='gcodedb.gdv')),
            ],
        ),
        migrations.AddField(
            model_name='g2code',
            name='gdvhdb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_g2codegdv', to='gcodedb.gdv'),
        ),
        migrations.AddField(
            model_name='g1code',
            name='gcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_g1codegcode', to='gcodedb.gcode'),
        ),
        migrations.AddField(
            model_name='g1code',
            name='gdvinq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gcodedb.gdv'),
        ),
        migrations.AddField(
            model_name='g1code',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_g1codeinquiry', to='gcodedb.inquiry'),
        ),
        migrations.AddField(
            model_name='g1code',
            name='lydoout',
            field=models.ManyToManyField(blank=True, null=True, related_name='fk_g1codelydoout', to='gcodedb.Lydoout'),
        ),
        migrations.AddField(
            model_name='g1code',
            name='lydowin',
            field=models.ManyToManyField(blank=True, null=True, related_name='fk_g1codelydowin', to='gcodedb.Lydowin'),
        ),
        migrations.AddField(
            model_name='g1code',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_g1codesupplier', to='gcodedb.supplier'),
        ),
        migrations.CreateModel(
            name='DanhgiaNSX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('dateupdate', models.DateField()),
                ('danhgiacode', models.ManyToManyField(null=True, related_name='fk_danhgiacode', to='gcodedb.Danhgiacode')),
                ('g2code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fk_danhgiag2code', to='gcodedb.g2code')),
                ('gdvdanhgia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_danhgiagdv', to='gcodedb.gdv')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='g1code',
            unique_together={('gcode', 'inquiry')},
        ),
    ]
