# Generated by Django 3.2.4 on 2021-08-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcode', models.ManyToManyField(related_name='fk_scanordergcode', to='gcodedb.Gcode')),
            ],
        ),
    ]
