# Generated by Django 3.2.4 on 2021-06-26 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='clientcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Contractclient', to='gcodedb.client'),
        ),
        migrations.AlterField(
            model_name='g1code',
            name='gcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_g1codegcode', to='gcodedb.gcode'),
        ),
        migrations.AlterField(
            model_name='g1code',
            name='inquirycode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_g1codeinquiry', to='gcodedb.inquiry'),
        ),
        migrations.AlterField(
            model_name='g1code',
            name='lydooutcode',
            field=models.ManyToManyField(related_name='fk_g1codelydoout', to='gcodedb.lydoout'),
        ),
        migrations.AlterField(
            model_name='g1code',
            name='lydowincode',
            field=models.ManyToManyField(related_name='fk_g1codelydowin', to='gcodedb.lydowin'),
        ),
        migrations.AlterField(
            model_name='g1code',
            name='suppliercode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_g1codesupplier', to='gcodedb.supplier'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='clientcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_Inquiryclient', to='gcodedb.client'),
        ),
    ]
