# Generated by Django 3.2.4 on 2021-07-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salescode', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='g1code',
            name='sales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_g1codesales', to='gcodedb.sales'),
        ),
    ]
