# Generated by Django 3.2.4 on 2021-07-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g1code',
            name='lydooutcode',
            field=models.ManyToManyField(blank=True, null=True, related_name='fk_g1codelydoout', to='gcodedb.Lydoout'),
        ),
        migrations.AlterField(
            model_name='g1code',
            name='lydowincode',
            field=models.ManyToManyField(blank=True, null=True, related_name='fk_g1codelydowin', to='gcodedb.Lydowin'),
        ),
    ]
