# Generated by Django 3.2.4 on 2021-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0002_scanorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanorder',
            name='gcode',
            field=models.ManyToManyField(null=True, related_name='fk_scanordergcode', to='gcodedb.Gcode'),
        ),
    ]
