# Generated by Django 3.2.4 on 2021-07-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0002_auto_20210707_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='g1code',
            name='markupinq',
        ),
        migrations.AlterField(
            model_name='danhgiansx',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podetail',
            name='ghichu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
