# Generated by Django 3.2.4 on 2021-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0002_auto_20210626_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g1code',
            name='resultinq',
            field=models.CharField(choices=[('Win', 'Win'), ('Out', 'Out')], default='Win', max_length=10, null=True),
        ),
    ]
