# Generated by Django 3.2.4 on 2021-07-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0003_auto_20210713_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='giaohang',
            name='ghichu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kho',
            name='ghichu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phat',
            name='ghichu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienve',
            name='ghichu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
