# Generated by Django 3.2.4 on 2021-06-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0003_alter_g1code_resultinq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientCode',
            new_name='clientcode',
        ),
    ]
