# Generated by Django 3.2.4 on 2021-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcodedb', '0005_auto_20210701_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='g1code',
            name='ghichu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='g1code',
            name='ngayout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='g1code',
            name='ngaywin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='g1code',
            name='resultinq',
            field=models.CharField(blank=True, choices=[('Win', 'Win'), ('Out', 'Out')], default='Win', max_length=10, null=True),
        ),
    ]
